import { Rajdhani,Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-primary",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-secondary",
});


export const metadata = {
  title: "Paraphol | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${rajdhani.variable} ${rubik.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>

      </body>
    </html>
  );
}
