import { Rajdhani } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const rajdhani = Rajdhani({
  subsets: ["latin"],
  weight: ['400','700']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${rajdhani.className} antialiased`}
      >
        <Navbar />
        <main>{children}</main>

      </body>
    </html>
  );
}
